ahupp/python-magic

- README.md
Cygwin is huge and slow.  File for Windows does not go through a posix translation layer, and are native windows libraries.  It is much less of a pain in the butt to use File for Windows.
> Change windows instructions

- magic.py
self.message was missing, causing `_handle509Bug` to fail.
> Fix MagicException

- setup.py
This is so that tools like https://github.com/brettcannon/caniusepython3 work properly.
> Add Python 3 trove classifier.

- setup.py
- Update the distutils license field to match MIT license as specified in:
* LICENSE file in repository
* Trove classifier
- Add Python :: 2 to trove classifier to declare explicit (PEP20) 2/3 compatibility
> Match license= to LICENSE, Add Python 2 to Trove

- MANIFEST.in
I've been putting together a build of python-magic for using [conda](http://conda.pydata.org) for [conda-forge](http://conda-forge.github.io). (See [here](https://github.com/conda-forge/staged-recipes/pull/1392).) For license compliance we like to bundle a copy of the original license file in with the build. Doing so requires that the license file be included with the source distribution. Adding this line to MANIFEST.in makes sure that the actual license file gets included with the source code.
> Added LICENSE to MANIFEST

- magic.py
The change lets to instantiate a Magic instance with the desired combination of flags and in particular have a mime type and encoding simultaneously if instantiated as
m = magic.Magic(mime=True, mime_encoding=True)
> Handling 'mime' and 'mime_encoding' independently

- magic.py
There are some Linuxes that have libraries search broken. This commit would add a reasonable fallback for these systems.
Otherwise python-magic does not work there having "magic" library installed and python-magic from Pypi.
> Added a fallback for Alpine to find library file

- magic.py
The suggested method for ensuring `sys.platform` check doesn't fail against `linux` platforms despite version is to check .startswith.  See:  http://stackoverflow.com/questions/10415942/python-sys-platform-linux2-but-not-linux3
This resolves `libmagic` detection on Alpine.
> Accommodate linux distros that return trailing version, i.e. Alpine

- test/test.py
Revert "update filetype reported by libmagic >=5.23 for keep_going=true"
This reverts commit 9d127ceaab1da0632128422ffd6a2d340bd3e778 and fixes https://github.com/ahupp/python-magic/issues/148.
> Fix the CI

- magic.py
> Handle incorrectly encoded file names

- .travis.yml
No need to download/install for failing builds
> Only install coveralls and codecov when needed

- test/test.py
Hi,
It seems that, when #96 was opened, there was no behaviour to select two acceptable output values for a test. Now that the mechanism exists, it's easy to make this test pass.
> Allow x-gzip as MIME type for gzip files, fixes #96

- MANIFEST.in
We at Gentoo currently have to rely on the GitHub tarball to run tests because one of the test data files is missing:
```
======================================================================
ERROR: test_descriptions (__main__.MagicTest)                           
----------------------------------------------------------------------                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                                
File "test/test.py", line 73, in test_descriptions …
```
> Include the whole test subdirectory in source distributions

- magic.pyi
- tox.ini
A stubfile was initially generated using `stubgen`, and then refined in
order to increase the accuracy of the core API methods.
Both `from_file` and `from_path`, both as independent functions and
class instace methods, have been annotated appropriately (taking
`Union[str, bytes]` and returning `Text`.
Resolves #174.
> 🐑 Create basic stub file for magic.py

- magic.py
Potentially `magic_open` may fail, and when python attempts to gc the Magic instance it fails with:
```
Exception ignored in: <function Magic.__del__ at 0x7f595ba06430>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/magic.py", line 129, in __del__
if self.cookie and magic_close:
AttributeError: 'Magic' object has no attribute 'cookie'
```
> Fix bug in Magic when destructor called too early

- .travis.yml
- setup.py
- test/run.py
- tox.ini
Add Python 3.9 to PyPI classifiers and test configs.
> Add support for Python 3.9

- setup.py
Type annotations are provided in the source file `magic/__init__.pyi`, but are not bundled in the package:
```console
$ python setup.py sdist
$ tar -tvf dist/python-magic-0.4.24.tar.gz | grep /magic/
drwx------ vivien/vivien     0 2021-12-30 10:47 python-magic-0.4.24/magic/
-rw------- vivien/vivien 14964 2021-12-30 10:43 python-magic-0.4.24/magic/__init__.py
-rw------- vivien/vivien  8316 2021-12-30 10:43 python-magic-0.4.24/magic/compat.py
-rw------- vivien/vivien  1168 2021-12-30 10:43 python-magic-0.4.24/magic/loader.py
-rw------- vivien/vivien     0 2021-12-30 10:43 python-magic-0.4.24/magic/py.typed
```
As a result, they are not available for typechecking when using the package in another project.
To ship them, `*.pyi` files should be included as part of `package_data`: …
> Include type stubs in package

- magic/loader.py
This is the name of the DLL file generated when using vcpkg to build libmagic:
https://github.com/microsoft/vcpkg/tree/master/ports/libmagic
> Add "magic-1.dll" to the list of DLL files to search for on Windows

- .travis.yml
- setup.py
- tox.ini
This PR adds Python 3.10 and 3.11 in CI runs/tox/trove classifier
> chore(tests): add Python 3.10 and 3.11 in CI runs/tox/trove classifier

- test/libmagic_test.py
- test/python_magic_test.py
[   12s] test/python_magic_test.py:53: in assert_values
[   12s]     self.assertIn(value, expected_value)
[   12s] E   AssertionError: 'PDF document, version 1.2, 2 page(s)' not found in ('PDF document, version 1.2', 'PDF document, version 1.2, 2 pages')
> Fix test suite with file 5.45

- magic/__init__.py
The builtin `open` will always follow symlinks.
Using `os.stat` is the easiest solution imo.
An alternative would be using `os.access` but that does not raise a FileNotFoundException so I chose `os.stat`.
As a sidenote I'd like to mention that setting `MAGIC_SYMLINK` is not possible, is it?
> fix: Don't raise FileNotFoundException on symlinks

- .travis.yml
The Python 3.13 release notes mention `python-magic` as one of the alternatives for `imghdr` which was removed from the Standard Library so let's ensure that its tests pass on Python 3.13 beta.
https://www.python.org/downloads/release/python-3130b1/
May raise `ModuleNotFoundError: No module named 'imghdr'` because Python 3.13 removes it from the Standard Library.
* https://docs.python.org/3/library/imghdr.html
> imghdr: use the projects [filetype](https://pypi.org/project/filetype/), [puremagic](https://pypi.org/project/puremagic/), or [python-magic](https://pypi.org/project/python-magic/) instead. (Contributed by Victor Stinner in [gh-104773](https://github.com/python/cpython/issues/104773).)
https://docs.python.org/3.13/whatsnew/3.13.html#pep-594-dead-batteries-and-other-module-removals
> Travis CI: Test on Python 3.13 beta

- .github/workflows/ci.yml
- test/python_magic_test.py
The Python 3.13 release notes mention `python-magic` as one of the alternatives for `imghdr` which was removed from the Standard Library so let's ensure that its tests pass on Python 3.13 beta.
https://www.python.org/downloads/release/python-3130b1/
May raise `ModuleNotFoundError: No module named 'imghdr'` because Python 3.13 removes it from the Standard Library.
* https://docs.python.org/3/library/imghdr.html
> imghdr: use the projects [filetype](https://pypi.org/project/filetype/), [puremagic](https://pypi.org/project/puremagic/), or [python-magic](https://pypi.org/project/python-magic/) instead. (Contributed by Victor Stinner in [gh-104773](https://github.com/python/cpython/issues/104773).)
https://docs.python.org/3.13/whatsnew/3.13.html#pep-594-dead-batteries-and-other-module-removals
> GitHub Action to replace Travis CI

- CHANGELOG
Cherry-pick https://github.com/ahupp/python-magic/pull/324
> Fix typos discovered by codespell

- magic/loader.py
Separate functions for each operating system.
```diff
+ def _lib_candidates_linux():
+     """Yield possible libmagic library names on Linux."""
+
+ def _lib_candidates_macos():
+     """Yield possible libmagic library names on macOS."""
+
+ def _lib_candidates_windows():
+     """Yield possible libmagic library names on Windows."""
```
Related to:
* #132
* #249
* #294
> loader.py: Separate functions for each operating system

- magic/loader.py
- test/python_magic_test.py
* A merge to reduce error spam during loading broke .so
loading in at least some (maybe all?) cases, where find_library
doesn't return an absolute path.
* Prematurely pushed some in-progress test changes that were super broken, all fixed now.
> Unbreak various things

- README.md
I wasn't able to really find the pip command quickly, so I thought this addition would help with readability and help people find the pip install command easier
> Small Fix to ReadMe that makes pip install command easier to see/find
